## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np
import os


# Import the time library and the datetime module from the datetime library 
import time
from datetime import datetime

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv('WeatherPy_database.csv')

city_data_df.head(10)

,City_ID,City,Lat,Lng,Current Description,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Guerrero Negro,27.9769,-114.0611,broken clouds,65.3,69,81,8.15,MX,2022-05-16 16:57:42
1,1,New Norfolk,-42.7826,147.0587,broken clouds,47.7,63,66,3.98,AU,2022-05-16 16:57:43
2,2,Kodiak,57.7900,-152.4072,scattered clouds,43.7,61,27,2.41,US,2022-05-16 16:57:43
3,3,Hobart,-42.8794,147.3294,scattered clouds,48.1,87,40,5.66,AU,2022-05-16 16:57:10
4,4,Katherine,-14.4667,132.2667,clear sky,77.3,50,0,2.57,AU,2022-05-16 16:57:44
5,5,Mataura,-46.1927,168.8643,moderate rain,55.5,98,77,0.73,NZ,2022-05-16 16:57:45
6,6,Lahaina,20.8783,-156.6825,scattered clouds,76.8,79,46,1.69,US,2022-05-16 16:57:46
7,7,Butaritari,3.0707,172.7902,overcast clouds,81.3,71,97,7.77,KI,2022-05-16 16:57:46
8,8,Saldanha,-33.0117,17.9442,scattered clouds,82.5,46,47,4.29,ZA,2022-05-16 16:57:47
9,9,Puerto Ayora,-0.7393,-90.3518,broken clouds,80.6,89,74,1.34,EC,2022-05-16 16:55:56

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(15)

,City_ID,City,Lat,Lng,Current Description,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
4,4,Katherine,-14.4667,132.2667,clear sky,77.3,50,0,2.57,AU,2022-05-16 16:57:44
6,6,Lahaina,20.8783,-156.6825,scattered clouds,76.8,79,46,1.69,US,2022-05-16 16:57:46
7,7,Butaritari,3.0707,172.7902,overcast clouds,81.3,71,97,7.77,KI,2022-05-16 16:57:46
8,8,Saldanha,-33.0117,17.9442,scattered clouds,82.5,46,47,4.29,ZA,2022-05-16 16:57:47
9,9,Puerto Ayora,-0.7393,-90.3518,broken clouds,80.6,89,74,1.34,EC,2022-05-16 16:55:56
10,10,Bambous Virieux,-20.3428,57.7575,scattered clouds,75.5,73,40,5.14,MU,2022-05-16 16:55:08
16,16,Port-Gentil,-0.7193,8.7815,scattered clouds,84.2,84,40,4.63,GA,2022-05-16 16:57:52
19,19,Kapoeta,4.7717,33.5903,scattered clouds,85.2,36,49,4.07,SS,2022-05-16 16:57:54
22,22,Vanimo,-2.6741,141.3028,broken clouds,78.9,85,59,1.42,PG,2022-05-16 16:57:56
23,23,Kavieng,-2.5744,150.7967,broken clouds,81.0,76,71,3.52,PG,2022-05-16 16:57:57
25,25,Rikitea,-23.1203,-134.9692,scattered clouds,77.3,68,44,8.87,PF,2022-05-16 16:57:58
26,26,Epe,6.5841,3.9834,light rain,84.4,75,99,3.88,NG,2022-05-16 16:58:00
30,30,Bluefields,12.0137,-83.7635,scattered clouds,77.1,100,40,2.06,NI,2022-05-16 16:58:02
31,31,Bubaque,11.2833,-15.8333,broken clouds,79.9,82,60,5.71,GW,2022-05-16 16:58:03
35,35,Adre,13.4667,22.2000,overcast clouds,86.8,35,89,6.63,TD,2022-05-16 16:58:06

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                233
City                   233
Lat                    233
Lng                    233
Current Description    233
Max Temp               233
Humidity               233
Cloudiness             233
Wind Speed             233
Country                233
Date                   233
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()

In [7]:
clean_df.count()

City_ID                233
City                   233
Lat                    233
Lng                    233
Current Description    233
Max Temp               233
Humidity               233
Cloudiness             233
Wind Speed             233
Country                233
Date                   233
dtype: int64

In [8]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
4,Katherine,AU,77.3,clear sky,-14.4667,132.2667,
6,Lahaina,US,76.8,scattered clouds,20.8783,-156.6825,
7,Butaritari,KI,81.3,overcast clouds,3.0707,172.7902,
8,Saldanha,ZA,82.5,scattered clouds,-33.0117,17.9442,
9,Puerto Ayora,EC,80.6,broken clouds,-0.7393,-90.3518,
10,Bambous Virieux,MU,75.5,scattered clouds,-20.3428,57.7575,
16,Port-Gentil,GA,84.2,scattered clouds,-0.7193,8.7815,
19,Kapoeta,SS,85.2,scattered clouds,4.7717,33.5903,
22,Vanimo,PG,78.9,broken clouds,-2.6741,141.3028,
23,Kavieng,PG,81.0,broken clouds,-2.5744,150.7967,

In [9]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
   
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    
    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    
    except (IndexError):
    
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [10]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df["Hotel Name"].replace('',np.nan, inplace=True)
clean_hotel_df = hotel_df.dropna(subset=["Hotel Name"])

clean_hotel_df.head(20)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
4,Katherine,AU,77.3,clear sky,-14.4667,132.2667,Pine Tree Motel
6,Lahaina,US,76.8,scattered clouds,20.8783,-156.6825,Lahaina Shores Beach Resort
7,Butaritari,KI,81.3,overcast clouds,3.0707,172.7902,Isles Sunset Lodge
8,Saldanha,ZA,82.5,scattered clouds,-33.0117,17.9442,Blue Bay Lodge
9,Puerto Ayora,EC,80.6,broken clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
10,Bambous Virieux,MU,75.5,scattered clouds,-20.3428,57.7575,Casa Tia Villa
16,Port-Gentil,GA,84.2,scattered clouds,-0.7193,8.7815,Fengshui Residence
19,Kapoeta,SS,85.2,scattered clouds,4.7717,33.5903,Eastgate Hotel
22,Vanimo,PG,78.9,broken clouds,-2.6741,141.3028,Vahmoneh Lodge Vanimo
23,Kavieng,PG,81.0,broken clouds,-2.5744,150.7967,Nusa Island Retreat
25,Rikitea,PF,77.3,scattered clouds,-23.1203,-134.9692,People ThankYou
26,Epe,NG,84.4,light rain,6.5841,3.9834,MAGVILLE HOTEL
30,Bluefields,NI,77.1,scattered clouds,12.0137,-83.7635,Nicaraguan Typical House Downtown
31,Bubaque,GW,79.9,broken clouds,11.2833,-15.8333,"Casa Dora, Bubaque"
39,Boyolangu,ID,75.5,broken clouds,-8.1181,111.8935,Yos ega cv
44,Bethel,US,81.4,broken clouds,41.3712,-73.4140,Courtyard by Marriott Danbury
51,Ledyard,US,83.4,scattered clouds,41.4398,-72.0142,Stonecroft Country Inn
54,Dalbandin,PK,85.6,clear sky,28.8947,64.4101,Sanjrani House
58,Acapulco,MX,88.5,scattered clouds,16.8634,-99.8901,HS Hotsson Smart Acapulco
59,Yenagoa,NG,80.7,moderate rain,4.9247,6.2642,Aridolf Resort Wellness and Spa

In [16]:
#8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [19]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [29]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=3)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
#fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))